cmake_minimum_required(VERSION 3.10)

project(GEMS)

set(CMAKE_CXX_STANDARD 17)

find_package(SFML 2.5 COMPONENTS graphics window system REQUIRED)

add_executable(GEMS
    main.cpp
    Game.cpp
    Board.cpp
    Gem.cpp
    Bonus.cpp
)

target_link_libraries(GEMS
    sfml-graphics
    sfml-window
    sfml-system
)